# https://dev.to/github/how-to-deploy-a-static-site-in-any-framework-of-your-choice-github-pages-neh
name: Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write
  pull-requests: write

jobs:
  unit_specs:
    name: Jest specs
    runs-on: ubuntu-latest
    steps:
    - name: Check out your repository using git
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run specs
      run: npm run test

    - name: Debugging Info
      run: |
        ls -al
        cat ./coverage-report.json
        env

    - name: Upload coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with: 
        coverage-file: ./coverage-report.json
        base-coverage-file: ./coverage-report.json
        github-token: ${{ secrets.GITHUB_TOKEN }}

  e2e_specs:
    name: Cypress specs
    runs-on: ubuntu-latest
    steps:
    - name: Check out your repository using git
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm run preview
        browser: chrome

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out your repository using git
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run linters
      run: npm run lint

  deploy:
    needs: [unit_specs, e2e_specs, linting]
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    environment: netlify
    steps:
    - uses: actions/checkout@v3
    
    # Sets the branch name as environment variable
    - uses: nelonoel/branch-name@v1.0.1

    - uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        build_directory: dist
        NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.SECRET_TOKEN }}
        NETLIFY_DEPLOY_TO_PROD: true
