# https://dev.to/github/how-to-deploy-a-static-site-in-any-framework-of-your-choice-github-pages-neh
name: Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out your repository using git
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run specs
      run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: specs

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Build project
      run: npm run build

  deploy:
    needs: build
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    environment: netlify
    steps:
    - uses: actions/checkout@v3
    
    # Sets the branch name as environment variable
    - uses: nelonoel/branch-name@v1.0.1

    - uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        build_directory: dist
        NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.SECRET_TOKEN }}
        NETLIFY_DEPLOY_TO_PROD: true
